version: '3.7'
services:
  database:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: '95883cbd4d258488'
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    ports:
      - 6379:6379
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222



